export const CREATE_PROJECT = 'CREATE_PROJECT'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID'
export const EDIT_PROJECT = 'EDIT_PROJECT'


// tasks
export const CREATE_TASK = 'CREATE_TASK'
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS'
export const DELETE_TASK = 'DELETE_TASK'
export const GET_TASK_BY_ID = 'GET_TASK_BY_ID'
