export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_TASK = 'CREATE_TASK'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS'